# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/ip/zxram/zxram.srcs/sources_1/bd/ram/ip/ram_xbar_0/ram_xbar_0.xci
# IP: The module: 'ram_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/ip/zxram/zxram.gen/sources_1/bd/ram/ip/ram_xbar_0/ram_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: v:/ip/zxram/zxram.srcs/sources_1/bd/ram/ip/ram_xbar_0/ram_xbar_0.xci
# IP: The module: 'ram_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/ip/zxram/zxram.gen/sources_1/bd/ram/ip/ram_xbar_0/ram_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
