# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/ip/zxram/zxram.srcs/sources_1/bd/ram/ip/ram_blk_mem_gen_0_0/ram_blk_mem_gen_0_0.xci
# IP: The module: 'ram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/ip/zxram/zxram.gen/sources_1/bd/ram/ip/ram_blk_mem_gen_0_0/ram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: v:/ip/zxram/zxram.srcs/sources_1/bd/ram/ip/ram_blk_mem_gen_0_0/ram_blk_mem_gen_0_0.xci
# IP: The module: 'ram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/ip/zxram/zxram.gen/sources_1/bd/ram/ip/ram_blk_mem_gen_0_0/ram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
